cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shoppingwebsite2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('website.urls', namespace='myapp')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from website.models import Product

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

website/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myapp:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, null=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myapp:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)    

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from website.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

orders/views.py
from django.shortcuts import render
from cart.cart import Cart
from .models import OrderItem
from .forms import OrderCreateForm


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])

            cart.clear()
            return render(request, 'order/ordered.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'order/order.html', {'cart': cart, 'form': form})

website/views.py
from django.shortcuts import render
from decimal import Decimal
from django.conf import settings
from django.urls import reverse
from paypal.standard.forms import PayPalPaymentsForm
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'list.html', {'category': category, 'categories': categories, 'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'detail.html', {'product': product, 'cart_product_form': cart_product_form})

def index(request):
    data=Product.objects.all()
    host = request.get_host()

    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': 100,#hardcode value
        'item_name': 'book',#hardcode value
        'invoice': '98966',#hardcode value
        'currency_code': 'USD',
        'notify_url': 'http://{}{}'.format(host, reverse('index')),
        'return_url': 'http://{}{}'.format(host, reverse('index')),
        'cancel_return': 'http://{}{}'.format(host, reverse('index')),
    }

    form = PayPalPaymentsForm(initial=paypal_dict)
    p={'product':data,'form':form}

    return render(request,'index.html',p)

templates/base.html
{% load static %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Tech-Shop</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="all,follow">

  <!-- Bootstrap CSS-->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <!-- Font Awesome CSS-->
  <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
  <!-- Google fonts - Roboto-->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,700">
  <!-- Bootstrap Select-->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
  <!-- owl carousel-->
  <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
  <!-- theme stylesheet-->
  <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
  <!-- Custom stylesheet - for your changes-->
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">

</head>
<body>
    <div id="all">
     
      <!-- Navbar Start-->
      <header class="nav-holder make-sticky">
        <div id="navbar" role="navigation" class="navbar navbar-expand-lg">
          <div class="container"><a href="{% url 'website:product_list' %}" class="navbar-brand home"><img src="{% static 'images/JTlogo.jpg' %}" alt="Universal logo" class="d-none d-md-inline-block" width="200px"><img src="img/logo-small.png" alt="Universal logo" class="d-inline-block d-md-none"><span class="sr-only">Universal - go to homepage</span></a>
            <button type="button" data-toggle="collapse" data-target="#navigation" class="navbar-toggler btn-template-outlined"><span class="sr-only">Toggle navigation</span><i class="fa fa-align-justify"></i></button>
            <div id="navigation" class="navbar-collapse collapse">
              <ul class="nav navbar-nav ml-auto">
                <li class="nav-item active">
                      <a href="{% url 'website:product_list' %}">Homepage</a>
                </li>
                <li class="nav-item "><a href="#">Contact <b class="caret"></b></a></li>
                <li class="nav-item "><a href="javascript: void(0)">About <b class="caret"></b></a></li>
              </ul>
            </div>
            <div id="search" class="collapse clearfix">
              <form role="search" class="navbar-form">
                <div class="input-group">
                  <input type="text" placeholder="Search" class="form-control"><span class="input-group-btn">
                    <button type="submit" class="btn btn-template-main"><i class="fa fa-search"></i></button></span>
                </div>
              </form>
            </div>
          </div>
        </div>
      </header>
      {% block content %}


      {% endblock %}
      <!-- FOOTER -->
      <footer class="main-footer">
        <div class="copyrights">
          <div class="container">
              <div class="col-lg-8 text-right text-center-md">
                <p>&copy; 2019. JT Online Shop</p>
              </div>
          </div>
        </div>
      </footer>
    </div>

      <!-- Javascript files-->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
      <script src="{% static 'vendor/waypoints/lib/jquery.waypoints.min.js' %}"> </script>
      <script src="{% static 'vendor/jquery.counterup/jquery.counterup.min.js' %}"> </script>
      <script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
      <script src="{% static 'vendor/jquery.scrollto/jquery.scrollTo.min.js' %}"></script>
    </body>

</html>

templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}

<div id="all"> 
                <div id="content">
                  <div class="container">
                    <div class="row bar">
                      <div class="col-lg-12">
                        <p class="text-muted lead">
                          {% with total_items=cart|length %}
                          {% if cart|length > 0 %}
                          <a href="{% url 'cart:cart_detail' %}">You have {{ total_items }} item{{ total_items|pluralize }} in your cart</a>
                          {% else %}
                          Your cart is empty.
                          {% endif %}
                          {% endwith %}
                        </p>
                      </div>
                      <div id="basket" class="col-lg-9">
                        <div class="box mt-0 pb-0 no-horizontal-padding">
                          <form method="get" action="shop-checkout1.html">
                            <div class="table-responsive">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th colspan="2">Product</th>
                                    <th>Quantity</th>
                                    <th>Unit price</th>
                                    <th>Discount</th>
                                    <th colspan="2">Total</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  {% for item in cart %}
                                  {% with product=item.product %}
                                  <tr>
                                    <td><a href="{{ product.get_absolute_url }}"><img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="" class="img-fluid"></a></td>
                                    <td>{{ product.name }}</td>
                                    <td>
                                      <form action="{% url 'cart:cart_add' product.id %}" method="post">{{ item.update_quantity_form.quantity }}
                                      {{ item.update_quantity_form.update }}
                                      <input type="submit" value="Update">
                                      {% csrf_token %}
                                      </form>
                                    </td>
                                    <td>${{ item.price }}</td>
                                    <td>$0.00</td>
                                    <td>${{ item.total_price }}</td>
                                    <td><a href="{% url 'cart:cart_remove' product.id %}"><i class="fa fa-trash-o"></i></a></td>
                                  </tr>
                                  
                                </tbody>
                                
                                {% endwith %}
                                {% endfor %}
                              </table>
                            </div>
                            <div class="box-footer d-flex justify-content-between align-items-center">
                              <div class="left-col"><a href="{% url 'website:product_list' %}" class="btn btn-secondary mt-0"><i class="fa fa-chevron-left"></i> Continue shopping</a></div>
                              <div class="right-col"><a href="{% url 'orders:order_create' %}" class="btn btn-template-outlined"><i class="fa fa-refresh"></i> Proceed to checkout</a></div>
                            </div>
                          </form>
                        </div>
          
                      </div>
                      <div class="col-lg-3">
                        <div id="order-summary" class="box mt-0 mb-4 p-0">
                          <div class="box-header mt-0">
                            <h3>Order summary</h3>
                          </div>
                          <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>
                          <div class="table-responsive">
                            <table class="table">
                              <tbody>
                                <tr class="total">
                                  <td>Order Total</td>
                                  <th>${{ cart.get_total_price }}</th>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                        </div>
                        
                      </div>
                    </div>
                  </div>
                </div>
          

{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}


 <div id="all">
      <div id="content">
        <div class="container">
          <div class="row bar">
            <!-- LEFT COLUMN _________________________________________________________-->
            <div class="col-lg-9">
              <div id="productMain" class="row">
                <div class="col-sm-6">
                    <div>
                     <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="" class="img-fluid">
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="box">
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                      <div class="sizes">
                        <h3>Price</h3>
                      </div>
                      <p class="price">${{ product.price }}</p>
                      <p class="text-center">
                      {{ cart_product_form }}
                      {% csrf_token %}
                        <button>
                         <input type="submit" class="btn btn-template-outlined"/><i class="fa fa-shopping-cart"></i> Add to cart
                        </button>
                      </p>
                    </form>
                  </div>
                </div>
              </div>
              <div id="details" class="box mb-4 mt-4">
                <p></p>
                <h4>Product details</h4>
                <blockquote class="blockquote">
                  <p class="mb-0"><em>{{ product.description|linebreaks }}</em></p>
                </blockquote>
              </div>
              <div id="product-social" class="box social text-center mb-5 mt-5">
                <h4 class="heading-light">Show it to your friends</h4>
                <ul class="social list-inline">
                  <li class="list-inline-item"><a href="#" data-animate-hover="pulse" class="external facebook"><i class="fa fa-facebook"></i></a></li>
                  <li class="list-inline-item"><a href="#" data-animate-hover="pulse" class="external gplus"><i class="fa fa-google-plus"></i></a></li>
                  <li class="list-inline-item"><a href="#" data-animate-hover="pulse" class="external twitter"><i class="fa fa-twitter"></i></a></li>
                  <li class="list-inline-item"><a href="#" data-animate-hover="pulse" class="email"><i class="fa fa-envelope"></i></a></li>
                </ul>
              </div>
            </div>
            <div class="col-lg-3">
              <!-- MENUS AND FILTERS-->
              <div class="panel panel-default sidebar-menu">
                  <div class="panel-heading">
                    <h3 class="h4 panel-title">Categories</h3>
                  </div>
                  <div class="panel-body">
                    <ul class="nav nav-pills flex-column text-sm category-menu">
                      <li class="nav-item"><a href="#" class="nav-link active d-flex align-items-center justify-content-between"><span>Clothes  </span><span class="badge badge-light">123</span></a><br/><br/></li>
                      <li class="nav-item"><a href="#" class="nav-link active d-flex align-items-center justify-content-between"><span>Electronics  </span><span class="badge badge-light">123</span></a><br/><br/></li>
                      <li class="nav-item"><a href="#" class="nav-link active d-flex align-items-center justify-content-between"><span>Furniture </span><span class="badge badge-light">123</span></a><br/><br/></li>
                      <li class="nav-item"><a href="#" class="nav-link active d-flex align-items-center justify-content-between"><span>Hardware </span><span class="badge badge-light">123</span></a><br/><br/></li>
                    </ul>
                  </div>
              </div>
            </div>
          </div>
    </div>


{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Index</title>
</head>
<body>
<marquee width="100%" direction="left" height="100px">
    <h3>Shop here</h3>
</marquee>

<table class="table" border="1">
    <thead>
    <tr><th>Name</th><th>Price</th><th>Image</th></tr>
     </thead>
    <tbody>
    {% for item in product %}
    <tr><td> {{item.name}}</td><td> {{item.price}}</td><td><img src="{% if item.image %}{{ item.image.url }}{% else %}Sorry no image{% endif %}"></td></tr>




    {% endfor %}
     {{ form.render }}
    </tbody>
    </table>
</body>
</html>

templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
  <!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default sidebar-menu">
                <div class="panel-heading">
                    <h3 class="h4 panel-title">Categories</h3>
                </div>
                    <div class="panel-body">
                        <ul class="nav nav-pills flex-column text-sm category-menu">
                          <li class="nav-item"><a href="{% url 'website:product_list' %}" class="nav-link active d-flex align-items-center justify-content-between"><span>All  </span><span class="badge badge-light">123</span></a><br/><br/></li>
                          {% for c in categories %}
                          <li {% if category.slug == c.slug %}class="nav-item"{% endif %}><a href="{{ c.get_absolute_url }}" class="nav-link active d-flex align-items-center justify-content-between"><span>{{ c.name }}</span><span class="badge badge-light">123</span></a><br/><br/>{% endfor %}</li>
                        </ul>
                    </div>
            </div>
        </div>

        <div class="col-lg-9">
            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'images/s1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'images/s2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'images/s3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>

        <div class="row products products-big">
            {% for product in products %}
            <div class="col-lg-3 col-md-6">
                <div class="product">
                    <div class="image"><a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt="" class="img-fluid image1"></a></div>
                    <div class="text" style="padding-top:10px;>
                        <h3 class="h5"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h3>
                        <p class="price">$ {{ product.price }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>   
    </div>
</div>

{% endblock %}

templates/order/order.html
{% extends "base.html" %}
{% block title %}
Checkout
{% endblock %}
{% block content %}



<div id="all">
      <div id="content">
        <div class="container">
          <div class="row">
            <div id="checkout" class="col-lg-9">
              <div class="box border-bottom-0">
                <form action="." method="post" class="order-form">
                
                  <ul class="nav nav-pills nav-fill">
                    <li class="nav-item"><a href="shop-checkout1.html" class="nav-link active"> <i class="fa fa-map-marker"></i><br>Address</a></li>
                  </ul>
                  <div class="content">
                    <div class="row">
                      <div class="col-sm-6">
                        <div class="form-group">
                          {{ form}}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="box-footer d-flex flex-wrap align-items-center justify-content-between">
                    <div class="right-col">
                      <button type="submit" class="btn btn-template-main">Continue to Delivery Method<i class="fa fa-chevron-right"></i></button>
                      {% csrf_token %}
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <div class="col-lg-3">
              <div id="order-summary" class="box mb-4 p-0">
                <div class="box-header mt-0">
                  <h3>Order summary</h3>
                </div>
                <p class="text-muted text-small">Shipping and additional costs are calculated based on the values you have entered.</p>
                <div class="table-responsive">
                  <table class="table">
                    <tbody>
                      
                      <tr class="total">
                        <td>Total</td>
                        <th>${{ cart.get_total_price }}</th>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

templates/order/ordered.html
{% extends "base.html" %}
{% block title %}
{% endblock %}
{% block content %}


<!-- Full Page Image Header with Vertically Centered Content -->
<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center" style:padding-top:100px;>
        <h1 class="font-weight-light"><br><br><br><br><br><br><br>Thank You</h1><br>
        <p class="lead">Your order has been successfully completed. Your order number is<strong>{{ order.id }}</strong>.<br><br><br><br><br><br><br><br></p>
      </div>
    </div>
  </div>
</header>

{% endblock %}